USE [master]
GO

/****** Object:  Database [C:\SELEST\PROGRAMS\PROJECTS\DATABASE\TRAININGTASKDB.MDF]    Script Date: 3/20/2020 4:54:16 PM ******/
DROP DATABASE [C:\SELEST\PROGRAMS\PROJECTS\DATABASE\TRAININGTASKDB.MDF]
GO


